# Generated by Django 4.0.4 on 2022-07-19 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_post_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='snippet',
            field=models.CharField(default='Click Like Above To Read BlogPost', max_length=200),
        ),
    ]
